import type { LucideIcon } from 'lucide-react';
import {
  BadgeDollarSign,
  BarChart3,
  Bot,
  Building2,
  CalendarDays,
  CircleDollarSign,
  ClipboardCheck,
  ClipboardList,
  ClipboardPlus,
  FileCheck2,
  Gavel,
  Globe2,
  Handshake,
  Hospital,
  LayoutDashboard,
  ListFilter,
  Receipt,
  Settings2,
  ShieldAlert,
  Stethoscope,
  UserRoundCheck,
  UsersRound,
} from 'lucide-react';
import type { WorkspaceView } from '../workspace-types';

export const navItems: { id: WorkspaceView; label: string; icon: LucideIcon }[] = [
  { id: 'overview', label: 'Command center', icon: LayoutDashboard },
  { id: 'queue', label: 'Work queue', icon: ListFilter },
  { id: 'registration', label: 'Registration desk', icon: ClipboardPlus },
  { id: 'patients', label: 'Patients', icon: UsersRound },
  { id: 'schedule', label: 'Schedule', icon: CalendarDays },
  { id: 'providers', label: 'Providers', icon: Hospital },
  { id: 'payers', label: 'Payers', icon: Building2 },
  { id: 'eligibility', label: 'Eligibility', icon: UserRoundCheck },
  { id: 'authorizations', label: 'Authorizations', icon: ClipboardCheck },
  { id: 'encounters', label: 'Encounters', icon: ClipboardList },
  { id: 'coding', label: 'Coding', icon: Stethoscope },
  { id: 'charges', label: 'Charges', icon: Receipt },
  { id: 'claims', label: 'Claims', icon: FileCheck2 },
  { id: 'denials', label: 'Denials & appeals', icon: ShieldAlert },
  { id: 'ar', label: 'A/R queue', icon: BarChart3 },
  { id: 'payments', label: 'Payments', icon: BadgeDollarSign },
  { id: 'contracts', label: 'Contracts', icon: Handshake },
  { id: 'leakage', label: 'Revenue leakage', icon: CircleDollarSign },
  { id: 'ai', label: 'AI workforce', icon: Bot },
  { id: 'packs', label: 'Country packs', icon: Globe2 },
  { id: 'rules', label: 'Rules', icon: Gavel },
  { id: 'settings', label: 'Operations', icon: Settings2 },
];
